---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ruanbekker/flask-mysql-guestbook:nunito
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_password
            - name: FLASK_APP
              value: application
            - name: MYSQL_USER
              value: app_user
            - name: MYSQL_DATABASE
              value: app_db
            - name: MYSQL_HOST
              value: mysql.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer
